import type { Metadata } from "next";
import ApolloSetting from '@/commons/settings/apollo-setting'
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <div className="app">
        <ApolloSetting>
          {children}
        </ApolloSetting>
      </div>
      </body>
    </html>
  );
}
